### ISSUE TITLE
Find a new OS X person

### ISSUE THREAD

**Issue by alexhultman** [alexhultman/node-lws#10]
I'm looking for someone with OS X that wants to provide builds which can be deployed via npm.

**Comment by LordMajestros** [comment]
Hello, I'm interested in this. What would I need besides XCode?

**Comment by LordMajestros** [comment]
Should I clone from https://github.com/warmcat/libwebsockets.git or https://github.com/alexhultman/node-lws.git ?

**Comment by alexhultman** [comment]
Hi.

You shouldn't need anything else than a clone of both repos. First you need to build libwebsockets according to the manual compilation instructions on the front page. Basically you need to configure CMake with

```cmake -DLWS_WITH_LIBUV=1 -DLWS_WITH_LIBEV=0 -DCMAKE_C_FLAGS=-fPIC -DLWS_WITHOUT_TESTAPPS=1 -DCMAKE_INSTALL_PREFIX=/usr .```

If this configuration works you can proceed and build it with make and then if that works you can install it with sudo make install (I prefer to install libraries in /usr).

Then you need to put Mac builds of Node.js in node-lws/node_versions like the README.md in that folders says. We aim for Node 4.x and 5.x support.

Then you can hit make in the node-lws folder and it will probably spew some errors that we need to fix one time and then it should roll smoothly from that point on.

Missing things can be installed using Homebrew (http://brew.sh/) but I'm not sure you will need anything.. no I do not think so.

**Comment by alexhultman** [comment]
4.3 for darwin (OS X): https://nodejs.org/dist/v4.3.0/
5.6: https://nodejs.org/dist/v5.6.0/

Extract them into node-lws/node_versions

**Comment by LordMajestros** [comment]
@alexhultman should the mac builds be called node-v4.3.0-mac-x64 and node-v56.0-mac-x64 or something else?

**Comment by alexhultman** [comment]
How far have you made it? Did you compile libwebsockets?

If the node-lws build passes you will get files in the dist folder like lws_darwin_46.node and lws_darwin_47.node. These are the output that needs to be deployed. You see I have already committed the corresponding linux builds.

**Comment by LordMajestros** [comment]
I compiled libwebsockets successfully and installed about 5 hours ago, had to do some work, continuing...

**Comment by LordMajestros** [comment]
I'm getting the following error: 

src/lws.cpp:23:10: fatal error: 'uv.h' file not found
#include <uv.h>

**Comment by LordMajestros** [comment]
Now getting the following

 src/lws.cpp:147:11: error: no member named 'lws_uv_sigint_cfg' in namespace 'lws::clws'
    clws::lws_uv_sigint_cfg(context, 0, nullptr);
    ~~~~~~^
src/lws.cpp:150:11: error: no member named 'lws_uv_initloop' in namespace 'lws::clws'
    clws::lws_uv_initloop(context, (lws::uv_loop_t *) (loop = uv_default_loop()),[](uv_signal_t *handle, int signum) {
    ~~~~~~^

**Comment by LordMajestros** [comment]
Now getting

```
clang: error: no such file or directory: 'dist/lws_darwin_46.node'
```
and

```
clang: error: no such file or directory: 'dist/lws_darwin_47.node'
```

**Comment by alexhultman** [comment]
Very nice. You seem to find solutions to problems and not just choke up. I
see you managed to install libuv from Homebrew? And then recompile
libwebsockets?

The last two errors are very strange and probably not part of any
programming error but rather something else. You can look in the Makefile
under Darwin and you will see the exact flags being passed to g++ (on OSX
g++ is an alias for clang++). It is the -o dist/lws_darwin_<module name
here>.node that seems to give you trouble. It should work because there
should be a folder called dist that it can put the output in.
Den 15 feb. 2016 6:26 em skrev "Dumbi Olise" <notifications@github.com>:

**Comment by alexhultman** [comment]
How are things going?

**Comment by LordMajestros** [comment]
I'm having problems linking. I'll detail them in a bit.

**Comment by alexhultman** [comment]
I just tested this on a Mac and I had to correct some flags to get things to work. Now it should compile and link and I tested this in Node 5.6 and it works and can receive connections.

**Comment by alexhultman** [comment]
https://github.com/alexhultman/node-lws/commit/de05f1a03c4ce6b34fd67d8889e6ee751fab829f

I wasn't aware Apple had locked down /usr even when using sudo, so I had to change the install path to /usr/local. I'll split the compilation instructions for libwebsockets into Linux and OS X chapters since they have some differences in flags.

**Comment by alexhultman** [comment]
So you need to add -DMACOSX_DEPLOYMENT_TARGET=10.7 and remove -DCMAKE_INSTALL_PREFIX=/usr when configuring for OS X. The builds I uploaded are probably only compatible with El Capitan because I didn't set -DMACOSX_DEPLOYMENT_TARGET=10.7 when compiling libwebsockets, only when compiling node-lws (it needs to be specified in both compilations).

**Comment by alexhultman** [comment]
Detailed information on compiling are available here: https://github.com/alexhultman/node-lws/blob/master/COMPILING.md

It should be a pretty straight forward compilation, you might need to install libuv and openssl into /usr/local/include.

**Comment by alexhultman** [comment]
@LordMajestros Did you get any further? I'm planning on buying a Mac, I need it for other projects anyways so it's no problem if you're having troubles.

**Comment by LinusU** [comment]
@alexhultman Have you considered using Travis for building? It's free for open source and provides both Linux and OS X environments.

You can use something like the following to make it build Linux + OS X, with Node 4 + 5:

```yaml
node_js:
  - "4"
  - "5"
os:
  - linux
  - osx
```

There is also a way to let Travis have access to keys which can be used to upload the release, without making the keys themselves public.

A `after_success` trigger can be used to trigger the uploading of the binary, as we do on the OpenRCT2 project here: https://github.com/OpenRCT2/OpenRCT2/blob/develop/.travis.yml#L20-L26

I'd be happy to help you set it up! Hopefully I'll have some time this weekend to look thru the code, but this project seems very interesting :raised_hands:

**Comment by alexhultman** [comment]
Never heard of Travis. Maybe in the future, but for now it's probably easier for me to just buy a Mac. I will need it for other things.

**Comment by LinusU** [comment]
[Travis CI](https://travis-ci.org) is a hosted CI solution that have become very popular in the node world (is probably popular elsewhere but I'm only active in the node community). The thing I like about it is that it's extremely easy to setup. Just drop a `.travis.yml` file in the root of the repository, add a Github hook url and you'r up and running.

I could help provide OS X builds as well, but the benefit of using Travis is that it would be automatically done as soon as something is merged to master. (or it could be as soon as someones makes a pull request, or any trigger really)

**Comment by herkyl** [comment]
:+1: for Travis

**Comment by LordMajestros** [comment]
I think you should look into travis. It really comes in handy even if you have a mac. @alexhultman

**Comment by alexhultman** [comment]
@LinusU If you look in COMPILING.md you can see the compilation steps. If this is easy to replicate without having Travis commit anything other than the .node libraries that would be appreciated. (And I do not like having 987468943643 lines of build scripts.)
