### ISSUE TITLE
Implement server options

### ISSUE THREAD

**Issue by alexhultman** [alexhultman/node-lws#12]
More options needs to be passable to the server constructor.

* port
* protocol name
* TCP keep-alive settings

Feel free to add to this list.

**Comment by herkyl** [comment]
* prefix or path

**Comment by alexhultman** [comment]
How is prefix and path relevant in the construction of the server?

**Comment by herkyl** [comment]
Yeah, some call it prefix (sockjs), some call it path (ws)

**Comment by alexhultman** [comment]
Yes that is something I need to add. Currently the protocol name is "default".
