### ISSUE TITLE
Support SSL connections

### ISSUE THREAD

**Issue by alexhultman** [alexhultman/node-lws#13]
Server options object needs these additions:

* sslCertificateFileName : String
* sslPrivateKeyFileName : String

**Comment by Rush** [comment]
This doesn't sound good. Couldn't we re-use node's stock SSL support if possible? node-lws would just get the decrypted byte-stream from node.

**Comment by Rush** [comment]
Also, please note that SSL is not just about the certificate and private key, there's much much more: https://nodejs.org/api/tls.html - OCSP, Forward Secrecy, cipher lists, session resumption - optimally we should just support the same set of options as TLS does.

I don't think that you can implement all of this stuff and nor do I think that you should. LWS should handle one thing well, and one thing only - that is, Web Sockets.

**Comment by alexhultman** [comment]
node-lws is a wrapper of libwebsockets. Libwebsockets itself already handle all of this stuff: https://libwebsockets.org/index.html

I will have everything wrapped up in a couple of days.

**Comment by alexhultman** [comment]
I just ran the test server with SSL. You specify a certificate and a private key and optionally a ca. Then you can specify cipher lists if you want. The three first arguments are just file paths and the last is a formatted string. Then you can also do custom OpenSSL stuff but that is not something I'm going to do right now. You can also control if you want to accept non-SSL connections or only SSL ones, so it's 5 arguments in total.

So if you have these things you should be able to set up a working wss WebSocket server in no time.

**Comment by alexhultman** [comment]
If you look at the Node.js 'https' module you can see pretty much identical settings: https://nodejs.org/api/https.html

**Comment by alexhultman** [comment]
I'll be implementing something like this interface as first version:

* ssl : Object
  * key : String (path)
  * cert : String (path)
  * ca : String (path)
  * ciphers : String
  * rejectUnauthorized : Boolean
