### ISSUE TITLE
Test 0.2.1

### ISSUE THREAD

**Issue by alexhultman** [alexhultman/node-lws#14]
0.2.1 is now a somewhat respectable release with Linux and OS X support. I would appreciate any testing feedback. Does it work on pre-El Capitan? It probably won't - that will be fixed in the next published version.

**Comment by herkyl** [comment]
Once OSX support is out I can run my own tests locally against lws transport adapter.

**Comment by alexhultman** [comment]
0.2.1 has OS X support. It is probably only working for El Capitan though.

**Comment by herkyl** [comment]
@alexhultman I will check it out later and report back here

**Comment by alexhultman** [comment]
Thanks, appreciated.

**Comment by herkyl** [comment]
I'm trying to wrap lws into a ws like wrapper. It seems I cannot use socket as key in a map. Is the best practice for this to use setUserData and getUserData?

**Comment by alexhultman** [comment]
The idea is that node-lws should mimic the ws interface as closely as possible without taking it too far so that performances are lost.

It is not possible to completely mimic ws without adding more overhead, one example is that in ws you get errors from sending on a closed socket, while in lws it simply crashes (there is no error checking, it is up to the user to track connections).

Also, setting a callback on every socket is performance suicide compared to setting it once and having it shared for every socket.

The socket "object" is an empty object in JS-land but holds 2 32-bit pointers in native land so there is no string evaluation of socket. I'm planning on adding a function to get the file descriptor of a socket so that it can be used in a map like this:

integer fileDescriptor = server.getSocketId(socket);

Then you can insert sockets in maps like this:

var map[server.getSocketId(socket)] = socket;

getSocketId is just a silly name I just invented, not decided yet.

**Comment by alexhultman** [comment]
But yes, currently you have to assign something to a socket when it is connected using setUserData and then use getUserData to get this value which can be used as a key.

**Comment by herkyl** [comment]
I got it working using:

```javascript
// set
server.setUserData(socket, id);
map.set(id, connection);

// get
var id = server.getUserData(socket);
var connection = map.get(id);
```

**Comment by herkyl** [comment]
I got most of the tests regarding Websockets working.
The server runs both a HTTP REST API and websocket API (on a different path). However lws does not allow running lws and httpServer on the same port. All tests using the REST API are not working.
Do you think this could be possible?

**Comment by alexhultman** [comment]
I haven't planned it yet but libwebsockets supports serving regular HTTP requests using the same server.

Maybe something like:

server.on('http', function(string request) {
server.end(some string as response);
});

I could add it in the future but I don't know if this is very prioritized yet? Because you could easily run a separate HTTP server for this right?

**Comment by herkyl** [comment]
Yeah I guess you're right. I will run a separate HTTP server on a different port.

**Comment by alexhultman** [comment]
The initial goal is to make a good WebSocket server, then the rest will follow.

**Comment by herkyl** [comment]
I will report back after getting the REST stuff working. I also have some stress tests that I can use to compare ws and lws.

**Comment by herkyl** [comment]
Got rest of the tests working. Also stress tests show that lws is taking **a lot** less memory. Once this is considered stable I can test it in production alongside other websocket servers to see how it behaves.

**Comment by alexhultman** [comment]
Yes it should be about <40% the memory of ws. I've had it tested with 1 million connections.

**Comment by LordMajestros** [comment]
@alexhultman other than tracking, is there any api to check if a socket is open/valid before writing to it?

**Comment by alexhultman** [comment]
Currently you have to track it yourself. It is possible to make the library track it for you but that would add some extra memory usage & runtime penalties to it. But why would you want to send using a closed socket? You can keep open sockets in some kind of container and remove them when they trigger the close event.

**Comment by alexhultman** [comment]
Thanks to everyone for the feedback on this version. I have noted the feature requests and will be working towards a new version shortly.
