### ISSUE TITLE
Can i use lws as replacement for ws, or will it possible ?

### ISSUE THREAD

**Issue by Pana** [alexhultman/node-lws#17]
FYI

**Comment by herkyl** [comment]
Yes, you can use lws as a replacement for ws. Though the APIs are a bit different. (Ws is more object oriented)

**Comment by alexhultman** [comment]
The goal is to focus on replacing ws as a server first. There is no client support yet (you can use ws for this).

**Comment by Pana** [comment]
This make sense, looking for your good news

**Comment by herkyl** [comment]
It's totally possible to wrap lws into a ws like wrapper atm. When I have time I will create an example for this.

**Comment by alexhultman** [comment]
@herkyl If it performs okay we could add it as a separate ws compatibility layer, or just add it to examples folder.

**Comment by ronkorving** [comment]
You may also wanna consider making a wrapper for https://www.npmjs.com/package/primus

**Comment by alexhultman** [comment]
I did start on a primus transformer: https://github.com/primus/primus/issues/433

But I do not know if this is the right way to go, primus seems very heavyweight and kind of goes against the purpose of this project. In primus every connection is represented by this massive "spark" with a bunch of extra data in it (HTTP headers and such). Currently a socket in node-lws is an empty object with 2 32-bit pointers attached. I would like to make this 1 32-bit pointer, or straight up a single integer.

But sure, an official primus transformer would be a nice milestone.

**Comment by alexhultman** [comment]
If you want to help out with the primus transformer you could check the issue out. It's only a few lines in total.

**Comment by alexhultman** [comment]
There is now primus support in my local fork: https://github.com/alexhultman/primus/commit/53a775e2e6bd2b2df9012d88e10d66e1575552cc

I'm looking to merge this upstream but I need to publish the 0.6.0 first.

**Comment by ronkorving** [comment]
Cool :+1:

**Comment by alexhultman** [comment]
If you upgrade to primus 5.0 you will have a new lws transformer to play with.

**Comment by alexhultman** [comment]
I'm working on a ws wrapper that will be exposed as lws.wsServer: https://github.com/alexhultman/node-lws/blob/master/dist/lws.js.
