### ISSUE TITLE
Implement sending functionality

### ISSUE THREAD

**Issue by alexhultman** [alexhultman/node-lws#2]
Currently there is only sending functionality in the C++ wrapper. This needs to be fixed for the Node.js wrapper. Sending on a closed socket will result in a crash - that's the libwebsockets way and it will be up to the user to track the 'closed' event accordingly.

**Comment by alexhultman** [comment]
@dankle Vi behöver kompilera om lws_darwin.node. Committar du den så publishar jag?

**Comment by alexhultman** [comment]
OS X binary is lagging behind.

**Comment by dankle** [comment]
It's not building:

../lws.cpp:95:9: error: non-constant-expression cannot be narrowed from type 'size_t'
      (aka 'unsigned long') to 'unsigned int' in initializer list [-Wc++11-narrowing]
        length,
        ^~~~~~

**Comment by dankle** [comment]
Ok, ny lws_darwin.node commitad.
