### ISSUE TITLE
How do you create a secure WebSocket Server?

### ISSUE THREAD

**Issue by ohenepee** [alexhultman/node-lws#20]
How do I replicate this?

```
var ws = require('ws');

var secureWebSockets = require('https').createServer({
  key: fs.readFileSync('./key.pem'), 
  cert: fs.readFileSync('./cert.pem')
}, function (req, res) {
  /* server code here */
});

var wsHTTPS = new ws.Server({server: secureWebSockets});

wsHTTPS.on('connection', function connection(ws) {
  var cookie = ws.upgradeReq.headers.cookie; // Get cookies
  /* ws code */
});
```

**Comment by alexhultman** [comment]
This is not yet wrapped but will be supported. See issue #13 for details. You would add the file paths to the server construction options.

**Comment by alexhultman** [comment]
I added documentation regarding ssl support. You also seem to want to read the header of the upgrade request, right? That should also be added then.

**Comment by ohenepee** [comment]
Thanks... waiting for the upgrade request part.

**Comment by alexhultman** [comment]
Yes so you are looking for an upcoming event I will probably call 'filter'. This event will be emitted before the connection and here you can read the HTTP headers involved in the upgrade. So it would look something like this:
```
server.on('filter', function(socket, headers) {
    console.log(headers.cookie);
    //return true or false to keep or close the connection (or something like this)
});
```

**Comment by alexhultman** [comment]
And there will also be a 'http' event in which you can do what you would have done in the http.Server (but it will probably be somewhat limited).

**Comment by alexhultman** [comment]
Yes so this is now fixed and in the next version you will be able to do this:
```
server.on('upgrade', function(socket, headers) {
    var cookie = headers.cookie;
});
```

**Comment by ohenepee** [comment]
Yay!! \o/

When is the NEXT VERSION by the way?

**Comment by alexhultman** [comment]
There should be a new version in some days or so.

**Comment by alexhultman** [comment]
#27 See if you can get the SSL thing working.

**Comment by alexhultman** [comment]
Did you get this working?

**Comment by ohenepee** [comment]
Will test today.... expect a feedback within 24 hours

**Comment by alexhultman** [comment]
Did it work?
