### ISSUE TITLE
Emit 'listening' event when listen successful and 'error' event if not

### ISSUE THREAD

**Issue by Rush** [alexhultman/node-lws#21]
Right now there's no way to tell if the server actually works. 

It should look like this
```js
let server = new lws.Server({ port: 56789999 });
server.on('error' ,(err) => {
  console.log('Error', err);
});
```

```js
let server = new lws.Server({ port: 5678 });
server.on('listening' ,() => {
  console.log('Listening');
});
```

**Comment by alexhultman** [comment]
Yes that is a good catch. Will add in the next version. Currently it will simply crash due to an uncaught (C++) exception if it cannot bind to the port.

**Comment by alexhultman** [comment]
ws docs only specify the "error" event. So that is the only one I implemented. If you didn't get an error it is up and running.
