### ISSUE TITLE
Allow to specify custom http agent

### ISSUE THREAD

**Issue by Rush** [alexhultman/node-lws#22]
I am not sure if this is possible due to nature of this module ... but in `ws` you can specify a custom Http agent like so:
```
      let ws = new WebSocket('ws://127.0.0.1', {
        agent: agent
      });
```
this allows for any custom communication layer or for http proxy.

Can lws be fed with connection sockets established by some 3rd party?

**Comment by alexhultman** [comment]
I don't think this is supported and it is not planned. Why would you need it?

**Comment by alexhultman** [comment]
Is this similar to #23?

**Comment by alexhultman** [comment]
I'm closing this as a duplicate of #23
