### ISSUE TITLE
32bit support

### ISSUE THREAD

**Issue by herkyl** [alexhultman/node-lws#29]
I was trying to install lws on a 32 bit linux and it fails when running. Is it planned to support 32bit linux?

**Comment by alexhultman** [comment]
This will of course depend on demand but I would rather not support 32bit for a number of reasons.

**Comment by herkyl** [comment]
Why not?

**Comment by alexhultman** [comment]
https://www.youtube.com/watch?v=pFlcqWQVVuU

**Comment by alexhultman** [comment]
I could add it in the future but currently I'm building everything manually so it would add maintenance. It is still possible to manually compile it for whatever architecture you want, but that is of course not a very pleasant user experience. Maybe when things start to calm down I can rethink this.
