### ISSUE TITLE
CPU 100% and errors

### ISSUE THREAD

**Issue by herkyl** [alexhultman/node-lws#30]
I finally tested out lws in production. It runs OK for ~5min but then gets locked in CPU 100%.

Logs are giving me messages like this:
```
Error in `node /data/socket/lib/index.js': double free or corruption (out): 0x000000000395dae0 ***
Error in `node /data/socket/lib/index.js': free(): invalid pointer: 0x0000000002984208 ***
Error in `node /data/socket/lib/index.js': double free or corruption (!prev): 0x00000000024a8830 ***
```

**Comment by alexhultman** [comment]
How are you using it? Are you sending on a closed connection?

**Comment by herkyl** [comment]
I keep track of connected users and send messages only to them but there is no double check before the send function. So there is a chance that the connection might be in some other state but have not emitted close yet. How do I check if a connection is open?

**Comment by alexhultman** [comment]
You cannot check if the socket is open or closed. You get the 'close' event when it is. After this point you are not allowed to send, then you get in all kinds of troubles.

**Comment by alexhultman** [comment]
In fact, you are not allowed to use the socket in any way after close.

**Comment by herkyl** [comment]
Then it should be working, since I am removing the connection from the connected connections list after the close event.

**Comment by alexhultman** [comment]
Can you provide some code that shows the usage and the problem?

**Comment by herkyl** [comment]
I have to narrow it down since the application is quite large itself.

**Comment by alexhultman** [comment]
Btw, what version is this?

**Comment by herkyl** [comment]
Its 0.2.1. I should upgrade it.

**Comment by herkyl** [comment]
Tried it with 0.5.1 and am still getting the same errors.

**Comment by alexhultman** [comment]
Okay but you need to provide some code otherwise I can't know if you are using it wrong or if there are problems.

**Comment by alexhultman** [comment]
Are you using a cluster? Do you fork? Are you running multiple instances of lws.Server?

**Comment by herkyl** [comment]
I am running multiple separate instances (one per core). I also tried running one instance and got the same error.

**Comment by alexhultman** [comment]
Did you strip it down? Send when you have an example.

**Comment by alexhultman** [comment]
Are you sending ping/pongs? Maybe it sends a ping after 5 minutes, I heard the server will crash on pings. Anyways - I will be releasing an updated version that fixes an unrelated stability issue regarding connections/disconnections.

**Comment by alexhultman** [comment]
Hey I have found something very unstable. My bench2 stress test can make it go down with 100% cpu like yours. Maybe I haven't run that test for a while. Will be checking this out. It crashes in the sending and I did some perf improvements there that I might have not checked.

**Comment by alexhultman** [comment]
Okay I have found one major issue. This is most certainly the problem you have.

**Comment by alexhultman** [comment]
Well I really need to update the benchmarking claims because the echo performance is much improved:

Echo performance: 99.9217 echoes/ms <- pffft!

It's really:

Echo performance: 114.782 echoes/ms

**Comment by alexhultman** [comment]
In C++: Echo performance: 143.02 echoes/ms

**Comment by ronkorving** [comment]
Or did you just buy a faster machine? :)

**Comment by alexhultman** [comment]
Okay could you test this with 0.5.2.

**Comment by alexhultman** [comment]
Hehe no I don't think so. I just reran the benchmarks:

Echo performance: 26.3108 echoes/ms (ws)
Echo performance: 121.684 echoes/ms (lws)

**Comment by ronkorving** [comment]
Cool :)

**Comment by herkyl** [comment]
Thanks, I will check it out and get back to you! :)

**Comment by herkyl** [comment]
The server has been running for half an hour now with no errors. It seems to be working. I will monitor it for a few days to see if any errors show up.

Closing for now.

Good work again :+1:

**Comment by alexhultman** [comment]
High five man, thanks for the report.
