### ISSUE TITLE
feature request: ping/pong support

### ISSUE THREAD

**Issue by reuzel** [alexhultman/node-lws#31]
Hi,

Thanks for taking the effort of building this module. Given its potential in performance wise this could become a very popular module!

Currently the solution supports keep-alive on TCP level. Problem with this is that these keep-alives may terminate at a local proxy server. To overcome this, we would like to see support for websocket ping/pong behavior. Ideally:
  * the lws module will automatically send pongs for incoming pings (in our current tests the server crashes when we send a ping)
  * the lws module would have the option to send pings and check for pongs based on two time intervals: 1) the frequency in which pings are send, and 2) the maximum wait time before a pong is to be received after a ping. Doing this in C++ would be more efficient than bothering the node application with this logic, especially when the numbers of connections grows.
  * Optionally, a received ping is forwarded to the node.js layer as an event, where the node.js app takes care of the pong responses and any side-effects.

Hope this helps,
Keep up the excellent work,
Joost

**Comment by alexhultman** [comment]
Yes I will check this in libwebsockets I think it support ping/pongs. Will also do some stability releases soon.

**Comment by alexhultman** [comment]
The ping crash was fixed in 0.5.2.

**Comment by herkyl** [comment]
Will the ping/pong work automatically or manually (like in ws)?

**Comment by alexhultman** [comment]
I don't know how it works yet but I'll find out. Maybe it is already responding to pings automatically, it seems that way.

**Comment by alexhultman** [comment]
Okay I have checked this out now.

1. is solved, that should be the case already (well now it doesn't crash at least).
2. is not done but should be added, yes. I should add 'pong' event and ping function.
3. is not possible becasue the server has no callback for pings (it automatically sends pongs)

```javascript
// get time
server.ping(socket, 'some payload');

server.on('pong', function () {
// note the time, print delay
});
```
