### ISSUE TITLE
Question: Connection limits

### ISSUE THREAD

**Issue by jessetabak** [alexhultman/node-lws#33]
Hi,

I'm running a performance test using this module and I'm having an issue I can't explain. 
Connecting the first 450.000 clients is really fast, at this moment there is still 65% of memory free and about 25% CPU usage. But after that it just stands still, no additional clients can connect for a few minutes. Do you have any idea what the problem might be or maybe have some tips on optimizing performance?

Thanks for the excelent work so far

Jesse

These are the specs and current configuration changes on my server:

#### Server specs
Ubuntu Server 14.04 VM on Azure
Quad Core
14GB RAM
#### /etc/sysctl.conf
```
fs.file-max = 1000000
fs.nr_open = 1000000
net.ipv4.netfilter.ip_conntrack_max = 1048576
net.nf_conntrack_max = 1048576
```
#### /etc/security/limits.conf
```
root soft nofile 1000000 
root hard nofile 1000000
* soft nofile 1000000
* hard nofile 1000000
```
#### Command line parameters
```
--nouse-idle-notification
--expose-gc (with a manual call interval of 30 sec to gc())
--max-old-space-size=8192
```

**Comment by alexhultman** [comment]
Hi,

The highest I have reached on my 16 gb machine is 1 million connections to/from localhost and I use these settings (Fedora 22):

*/etc/security/limits.d/custom.conf*
root soft nofile 1500000
root hard nofile 1500000
* soft nofile 1500000
* hard nofile 1500000

*/etc/sysctl.conf*
fs.file-max = 2100000
fs.nr_open = 2100000
net.nf_conntrack_max = 2100000

*per session, just punched in the terminal*
sudo sysctl net.ipv4.tcp_tw_recycle=1
sudo sysctl net.ipv4.tcp_tw_reuse=1
sudo sysctl net.nf_conntrack_max=1500000

As you can see I have some overlapping settings and I don't really know what everything is about but it works fine. You see I have 2x on some settings, I think you need 2x on fs.file-max to reach 1 million (one client size, one server side), but I'm not 100% sure about this.

**Comment by alexhultman** [comment]
You can drop the GC settings because it's not using the GC at all, only if you use the http.Server. (Well, it uses the GC a tiny bit but not in a significant way).
