### ISSUE TITLE
Compatibility for windows

### ISSUE THREAD

**Issue by renesamaral** [alexhultman/node-lws#34]
hi! i installed the module via NPM on a windows machine and when i run my app i got this error:

"C:\Program Files (x86)\JetBrains\WebStorm 11.0.3\bin\runnerw.exe" "C:\Program Files\nodejs\node.exe" app.js
module.js:339
    throw err;
    ^

Error: Cannot find module './lws_win32_46'

My intention is to use this module in a linux machine in production in a VPS. but atm, i'm trying to use in  my windows DEV  environment, any possibilites to compiles this module to work in Windows ?

**Comment by alexhultman** [comment]
Sorry there is no Windows support (yet?). It is not impossible to add (libwebsockets exists for Windows) but I don't have the OS and currently we use a couple of Unix-only features. The libwebsockets libuv backend uses uv_poll_t which is fast on Unix but should (allegedly) be slow on Windows as one example.

**Comment by renesamaral** [comment]
Ok, no problem! i will setup a VM with linux! Nice job :)
