### ISSUE TITLE
Strange behavior when echoing a big buffer

### ISSUE THREAD

**Issue by lpinca** [alexhultman/node-lws#37]
I was running a little benchmark to see how good `lws` was at echoing a big buffer (~100 MB) and noticed something strange:
```js
'use strict';

const prettyBytes = require('pretty-bytes');
const crypto = require('crypto');
const lws = require('lws');
const ws = require('ws');

const size = 100 * 1024 * 1024;
const buf = crypto.randomBytes(size);

const server = new lws.Server({
  perMessageDeflate: false,
  port: 3000
});

server.on('message', (socket, data) => server.send(socket, data, true));

const start = Date.now();
const socket = new ws('ws://localhost:3000', { perMessageDeflate: false });

socket.on('open', () => socket.send(buf, { binary: true }));
socket.on('message', () => {
  const end = Date.now();
  const elapsed = (end - start) / 1000;

  console.log(`${elapsed.toFixed(2)}s ${prettyBytes(size / elapsed)}/s`);
});
```
When you run the above code you'll see a bunch of console messages instead of a single one. It seems that the original message is split in chunks of 4096 bytes and each chunk is then sent back to client as a different message.

I've seen the same behaviour in both OS X and Linux. Node version is 5.8.0.

**Comment by alexhultman** [comment]
I will take a look at this then.

**Comment by alexhultman** [comment]
What's happening is that you are getting multiple 'message' callbacks and sending multiple small messages. The message callback will not buffer up huge messages but only give you fragments. So I need to fix the message callback to give more information, there is a "remainingBytes" equivalent I can add, then you need something similar for the send so that you can send fragments of a message and have it returned as one message at the client.

**Comment by lpinca** [comment]
I understand. This is a bit inconsistent with existing WeSocket modules. `ws`, `faye-websocket`, `node-yawl` all fire a single `message` event no matter what the size of the message is.

**Comment by alexhultman** [comment]
Yep but I could probably add 2 callbacks: one simple and slow and one more complex with the ability to control your own buffering.

**Comment by lpinca** [comment]
It makes sense. Unrelated, but if `perMessageDeflate` is set to `true` nothing happens.

**Comment by alexhultman** [comment]
It doesn't work?

**Comment by lpinca** [comment]
Connection is established, some data is received server-side, then it hangs.
I'm using the same example above.

**Comment by alexhultman** [comment]
64.18s 1.63 MB/s

Is that fast?

**Comment by lpinca** [comment]
1.01s 103.31 MB/s with `ws` and `perMessageDeflate` disabled.

**Comment by alexhultman** [comment]
Ah, just tested I got 1.12s 93.46 MB/s.

**Comment by alexhultman** [comment]
Okay so I'll fix this up.

**Comment by lpinca** [comment]
My machine is super slow (it's a 2009 macbook pro :smile:).
This is the code for `ws`:
```js
'use strict';

const prettyBytes = require('pretty-bytes');
const crypto = require('crypto');
const http = require('http');
const ws = require('ws');

const size = 100 * 1024 * 1024;
const buf = crypto.randomBytes(size);

const server = http.createServer();
const wss = new ws.Server({
  perMessageDeflate: false,
  clientTracking: false,
  noServer: true
});

server.on('upgrade', (req, socket, head) => {
  wss.handleUpgrade(req, socket, head, socket => {
    socket.on('message', data => socket.send(data, { binary: true }));
  });
});

server.listen(3000, () => {
  const start = Date.now();
  const socket = new ws('ws://localhost:3000', { perMessageDeflate: false });

  socket.on('open', () => socket.send(buf, { binary: true }));
  socket.on('message', () => {
    const end = Date.now();
    const elapsed = (end - start) / 1000;

    console.log(`${elapsed.toFixed(2)}s ${prettyBytes(size / elapsed)}/s`);

    socket.close();
    server.close();
  });
});
```

**Comment by lpinca** [comment]
also install `bufferutil` and `utf-8-validate` for `ws`.

**Comment by alexhultman** [comment]
Okay I got 0.36s 292.08 MB/s.

**Comment by alexhultman** [comment]
I can get it up to about `0.61s 171.9 MB/s` with the fragment-send-stuff. So for the moment it is probably a better idea to use ws if you plan on sending huge messages.

**Comment by alexhultman** [comment]
But I guess one can argue against using the WebSocket protocol at all when just sending a lot of binary data. There are much better protocols to use for that purpose - you have a lot of overhead in WebSockets compared to a regular TCP socket if you only want pure data throughput.

**Comment by lpinca** [comment]
Will run a similar test with many small buffers later where `lws` should shine.

**Comment by alexhultman** [comment]
Yeah I think a graph over different sizes should show how it scales pretty nicely. I did a profiling of the server when echoing this large message and it is spending 99% of the time in the parser so maybe the parser is faster in ws, while the overall latency of events and stuff are faster so when having a small message to parse it doesn't matter that the parser is a little bit slower. That's my guess.

**Comment by alexhultman** [comment]
What happens in ws when someone sends a message of size 500 GB? I will either just buffer up and crash or it somewhere needs to limit the message. In some sense, that is already what lws does - it only accepts about 4kb of message. That should be enough for most use cases and if it is not I would rather have the user of the library do the buffering to avoid leaving a security problem in the library. I think that adding information to the 'message' callback about remainingBytes and such would be enough. Ad maybe expose a way to set the max buffer size.

**Comment by alexhultman** [comment]
```
Event: 'message'

function (data, flags) { }

Is emitted when data is received. flags is an object with member binary.
```
This is kind of a lie, it cannot possibly handle 500 GB of message if you only have 16 GB of RAM. It will probably just emit an 'error' event and drop the message.

**Comment by alexhultman** [comment]
I think the most important missing piece is to get an integer "remainingBytes" that is either 0 for complete or non-zero for a fragmented message. Then the user can decide how to buffer it up or just close the socket if it becomes too long.

But I would also want to support sendFragmented so that you can build an echo server that can echo huge messages without doing any kind of buffering (you just receive fragments, and send fragments).

**Comment by lpinca** [comment]
`faye-websocket` has a [`maxLength`](https://github.com/faye/faye-websocket-node#initialization-options) option. Something similat has been recently added in `ws` but I can't rember how it is called.

**Comment by alexhultman** [comment]
There is the rx_buffer_size which is a similar thing but it is not guaranteed to allow that much, it's up to the kernel to accept *max* that much in the buffer. I can add access to that variable and also add the remainingBytes in the message. The rest is something I would like to add in a separate "simplification layer" along with tracking of connections etc. I want to have the core of the library minimal and without any complexities that can cause problems. I guess I should write some kind of ws-like JS wrapper that does all of these things automagically.

**Comment by alexhultman** [comment]
What do you think of something like this:

var lws = require('lws');
var server = lws.Server({...}); <- minimal core
var wrappedServer = lws.WrappedServer({...}); <- ws-like objectier-orienteder

Any suggestions for other names? Other ideas how to wrap it?

lws.WSServer({...}) or lws.wsServer({...}) <- I like that last name!

**Comment by danielbankhead** [comment]
Hey Alex, why not create a few options for `lws.Server()` that would allow us control the buffer without a separate wrapper? What do you think of the following?

- `concatBuffer` [Boolean = default `true`]
- `concatBufferLimit` [Integer = default `4096`] - in bytes. Used when `concatBuffer === true`
- `concatBufferTruncate` [Boolean = default `false`] - if true truncate the messsage, if false, remove it from memory and do not emit `message`. Used when `concatBuffer === true`

Great work by the way. I plan on using lws for my future projects > ws & socket.io.

**Comment by alexhultman** [comment]
Maybe I'll move the buffering into the library, will think about it.

**Comment by lpinca** [comment]
As expected `lws` is great when echoing small buffers. Here are my results:
```
big buffer (ws): 0.99s 105.81 MB/s
big buffer (faye): 1.21s 86.73 MB/s
small buffers (ws): 1.07s 4.59 MB/s
small buffers (faye): 1.30s 3.79 MB/s
small buffers (lws): 0.69s 7.16 MB/s
big buffer permessage-deflate (ws): 11.43s 9.18 MB/s
big buffer permessage-deflate (faye): 5.93s 17.69 MB/s
small buffers permessage-deflate (ws): 5.21s 946.18 kB/s
small buffers permessage-deflate (faye): 5.44s 905.98 kB/s
small buffers permessage-deflate (lws): 3.48s 1.42 MB/s
```
Code is [here](https://gist.github.com/lpinca/389b2fb022eee147d11a). We need a way to gracefully shut down `lws` server to make the process exits cleanly.

**Comment by alexhultman** [comment]
Okay I didn't finish the buffering yet but at least you can get the remainingBytes now and control the options.bufferSize. I think there is a bug when you pass a large buffer to the send function, that's why I first got a 60 second time. I need to check this out but I'm pretty sure this is in libwebsockets itself.

**Comment by alexhultman** [comment]
Next version will also have a graceful shutdown. I have a patch for libwebsockets, just need to test it some more. Seems to work pretty nicely.

**Comment by lpinca** [comment]
> There is the rx_buffer_size which is a similar thing but it is not guaranteed to allow that much, it's up to the kernel to accept max that much in the buffer.

What is the upper bound for the `bufferSize` option? I understand it depends on the system, but is there any documentation? The only thing I found is [this](https://libwebsockets.org/libwebsockets-api-doc.html).

I tried to play with `bufferSize` and the bigger I make it the faster it gets, but it only works up to ~5 MB, after that it seems to fail silently.

**Comment by alexhultman** [comment]
rx_buffer_size sets the SO_SNDBUF:

```
SO_SNDBUF
              Sets or gets the maximum socket send buffer in bytes.  The
              kernel doubles this value (to allow space for bookkeeping
              overhead) when it is set using setsockopt(2), and this doubled
              value is returned by getsockopt(2).  The default value is set
              by the /proc/sys/net/core/wmem_default file and the maximum
              allowed value is set by the /proc/sys/net/core/wmem_max file.
              The minimum (doubled) value for this option is 2048.
```

**Comment by alexhultman** [comment]
My max limit is just 200 kb so maybe I could have got better results by increasing the system max to get a buffer of a couple of MBs?

**Comment by lpinca** [comment]
Yes, I think so, the bottleneck seems to be buffer concatenation.

**Comment by alexhultman** [comment]
There is no concat, it just gives you the fragments as is. But yeah the buffer size affects perf. When I got the ~170MB/sec I used a larger bufferSize and got better perf but since my limit was only 200kb (obviously) maybe that limited things. I don't know exactly, but a smaller buffer is probably better for scaling if you only plan on sending small messages. But see if you can change your system max and see if that makes it any better?

**Comment by lpinca** [comment]
Yes, I meant the concat from js land to store multiple fragments as a single message, but it's not only that, even with no concat `bufferSize` makes a huge difference.

**Comment by alexhultman** [comment]
The only reference I can find is this:

```c

		/*
		 * create the frame buffer for this connection according to the
		 * size mentioned in the protocol definition.  If 0 there, use
		 * a big default for compatibility
		 */

		n = wsi->protocol->rx_buffer_size;
		if (!n)
			n = LWS_MAX_SOCKET_IO_BUF;
		n += LWS_PRE;
		wsi->u.ws.rx_ubuf = lws_malloc(n + 4 /* 0x0000ffff zlib */);
		if (!wsi->u.ws.rx_ubuf) {
			lwsl_err("Out of Mem allocating rx buffer %d\n", n);
			return 1;
		}
		wsi->u.ws.rx_ubuf_alloc = n;
		lwsl_info("Allocating RX buffer %d\n", n);
#if LWS_POSIX
		if (setsockopt(wsi->sock, SOL_SOCKET, SO_SNDBUF,
			       (const char *)&n, sizeof n)) {
			lwsl_warn("Failed to set SNDBUF to %d", n);
			return 1;
		}
#endif
```

I cannot see any SO_RCVBUF?

**Comment by alexhultman** [comment]
You could change your systems default values of the read buffer:

/proc/sys/net/core/rmem_default
/proc/sys/net/core/rmem_max

**Comment by lpinca** [comment]
This is exactly what I'm trying to do in VM.

**Comment by alexhultman** [comment]
I'm looking at the parser code and it looks *very* unoptimized for reading large messages. It makes massive function calls and jumps for every byte, even when in a very simple state where it really only copies bytes into a buffer. When I profiled it I found 99% CPU time being spent in lws_interpret_incoming_packet so if I do some optimizations here it could *really* improve the overall perf for huge messages.

**Comment by lpinca** [comment]
Actually on this VM (with tuned up rmem and wmem) it doesn't seem to change much:
```
big buffer (lws): 1.43s 73.58 MB/s    # without bufferSize
big buffer (lws): 1.58s 66.37 MB/s    # with bufferSize set to the actual size of the buffer
```
On OS X:
```
big buffer (lws): 1.51s 69.4 MB/s    # without bufferSize
big buffer (lws): 1.41s 74.37 MB/s  # with bufferSize set to 5 MB
```

**Comment by alexhultman** [comment]
Yeah that seems the same I got. The bufferSize (rx_buffer_size) affects the SO_SNDBUF but also the parsers buffer. That's what is making it faster, not the sending buffer. But yeah, the parser itself is bottlenecking it.

**Comment by alexhultman** [comment]
lws_interpret_incoming_packet calls lws_rx_sm which handles the specific *byte* according to the parsers state. This is all fine and dandy when in different states but when in the state LWS_RXPS_PAYLOAD_UNTIL_LENGTH_EXHAUSTED it really only puts the byte in the parsers buffer. Doing all of this for every byte is like, 32 times slower than what it could be if you used vectorization and stuff. I think this specific case is completely unoptimized because no one has sent huge data before.

**Comment by alexhultman** [comment]
I have a patch that bypasses the slow path of the parser for payload data. Seems to work, need to benchmark it somehow.

**Comment by lpinca** [comment]
Awesome!

**Comment by alexhultman** [comment]
Okay with a parse buffer of 200kb (very small!) it takes 540ms to receive 100MB with the original parser. With this bypass it takes 196ms. I just got it to work and I'm sure I can optimize it further but now it should be able to scale better with a larger buffer (I'm sure it will scale *a lot* better with a larger buffer because now it completely bypasses all of the complex parser core when in this very simple state.

When I did my fragmented send before I has about 0.6s time while ws had 0.3, that makes sense because the 0.54s receive was the bottleneck. Now it should probably be able to echo the buffer in about 0.2s which is faster than ws. Let's see when I'm done.

**Comment by alexhultman** [comment]
With further optimizations I get 59ms. 10x faster.

**Comment by alexhultman** [comment]
I have submitted a pull request now so it might get merged. It should *by far* outperform ws.

**Comment by alexhultman** [comment]
I think I get about 551.88 MB/s now.

**Comment by alexhultman** [comment]
Yeah, there is a real bug when sending a large buffer. It completely just stops and takes 1 minute to send it all. I can only get it to work by sending small fragments. I'll open a separate bug for this.

**Comment by alexhultman** [comment]
You'll need a faster client to benchmark this. I can't go beyond ~500 MB/sec when using ws as client. The server is only at 8% CPU usage while the ws client process is at 100%, bottlenecking it all:

```
Size of message: 104857600
0.22s 483.21 MB/s
Size of message: 104857600
0.20s 514.01 MB/s
Size of message: 104857600
0.21s 499.32 MB/s
Size of message: 104857600
0.21s 489.99 MB/s
Size of message: 104857600
0.21s 506.56 MB/s
Size of message: 104857600
0.21s 504.12 MB/s
Size of message: 104857600
0.21s 506.56 MB/s
Size of message: 104857600
0.21s 501.71 MB/s
Size of message: 104857600
0.21s 504.12 MB/s
Size of message: 104857600
0.21s 496.96 MB/s
```

**Comment by alexhultman** [comment]
A good estimate would be about 1 GB/sec. I ran 3 ws clients simultaneously sending 100 MB all the time to the same server process, taking the average latency. 340 MB/sec * 3 = 1020 MB/sec aka ~1 GB/sec. As a comparison, the ws server runs hot with only one client connected, averaging at 330 MB/sec.

This is however using the new sendFragment which means I do not buffer up the messages before sending them. I cannot test with buffering because of bug #39.

**Comment by lpinca** [comment]
Great job @alexhultman.

**Comment by alexhultman** [comment]
I've added the 'fragment' event for getting unbuffered messages. The 'message' event now loses its bytesRemaining parameter, but is now buffered. It simply truncates the message on overflow.

**Comment by alexhultman** [comment]
Okay there is now 0.7.0, this one buffers messages (which is the main topic in this bug report) and the other flaws are tracked in separate reports. We should update the Primus dependencies to 0.7.x and see if it passes the integration tests.

**Comment by lpinca** [comment]
There is something with primus since `lws@0.6.3`:
```
$ node_modules/.bin/mocha test/lws.integration.js 


  Transformer: lws
    .Socket
      ✓ exposes a compatible socket
```
Only one test is run, 0.6.2 work fine.

**Comment by alexhultman** [comment]
Yeah I broke the server.close with this commit: https://github.com/alexhultman/node-lws/commit/d9638ff42574bb125b4a7ad7327febdfbddd55e9

You can use 0.6.2 until I have fixed this for real. #40

**Comment by alexhultman** [comment]
Wait, I'll just unpublish the 0.6.3.

**Comment by alexhultman** [comment]
We can continue in #40 and #39
