### ISSUE TITLE
Improve ws wrapper

### ISSUE THREAD

**Issue by alexhultman** [alexhultman/node-lws#38]
With 0.6.2 there is an initial ws-like wrapper that is very limited but seems to work pretty okay. It needs improvements. Source is all JS and is located in dist/lws.js.

**Comment by lpinca** [comment]
I saw that you implemented clients tracking with a [doubly linked list](https://github.com/alexhultman/node-lws/blob/8be281be850fdea9f7f047210f8355059cb8d73e/dist/lws.js#L11).

Is it to have insert and delete operations in O(1) or are there other reasons?

In the former case we can use a [Set](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Set). If I'm not wrong V8 uses hash tables for sets and maps so time complexity should generally be O(1). The advantage is that a set is a lot easier to maintain.

**Comment by alexhultman** [comment]
I think a doubly linked list is the most performant & lightweight in this case. With time I'll probably solve it in C++ (libwebsockets has broadcast(ish) functionality, but I haven't figured out how to use it).
