### ISSUE TITLE
Sending a large buffer is unreasonably slow

### ISSUE THREAD

**Issue by alexhultman** [alexhultman/node-lws#39]
When the buffer doesn't fit in a single send buffer, it takes forever to send it. Probably needs patches to the libuv libwebsockets backend to fix.

**Comment by alexhultman** [comment]
@lpinca I have found that sending a large buffer works when bufferSize is set, but it simply times out when not set. You managed to send a large buffer, does it work when you leave the bufferSize unset?

Large permessage deflate receives disconnects the client for in any case.

**Comment by alexhultman** [comment]
For me, anything below about 32-33 kb buffer takes 63 seconds, while 33 and up takes less than a second to send.

**Comment by alexhultman** [comment]
This was a very strange bug in libwebsockets that is now solved but not merged yet. Will be fixed in 0.7.1.

**Comment by lpinca** [comment]
Yeah it also worked with `bufferSize` unset, but with it set to 5 MB it was 3x times faster.
I also noticed that it didn't work with `perMessageDeflate` on.

It's great to hear that it's going to be fixed.

**Comment by alexhultman** [comment]
Yep the perMessageDeflate issue is something I need to look into. It seems I'm the only one affected by this(#39) bug.

**Comment by lpinca** [comment]
I also noticed that when `perMessageDeflate` is on the `message` listener receives fragments instead of a full buffer.

**Comment by lpinca** [comment]
I'm posting few results here for reference. `1` is when the message sent from client, is received on the server, `2` when the message reaches the client again.

** bufferSize: 5MB **
```
1) size: 104857600 time: 0.718s
2) size: 104857600 time: 1.326s
```

** bufferSize: unset **

```
1) size: 104857600 time: 0.671s
2) size: 104857600 time: 3.073s
```

`node-lws` version is `0.7.0`.

**Comment by alexhultman** [comment]
0.7.1 will be faster, but the fastest is to just use the 'fragment' event and sendFragment. It's hard to get any faster when doing this huge buffering. You should also do multiple runs and average the results. And you might need to have multiple client processes and one server process to really stress the server.

**Comment by lpinca** [comment]
Using `fragment` event and `sendFragment`:

**bufferSize: 5MB**
```
1) size: 104857600 time: 0.92s
2) size: 104857600 time: 1.01s
```

**bufferSize: unset**
```
1) size: 104857600 time: 1.836s
2) size: 104857600 time: 3.114s
```

**Comment by alexhultman** [comment]
When using fragments you need more clients to stress it. I needed 3 clients to stress the server to like 80%.

**Comment by lpinca** [comment]
Sorry for spamming, more data from https://gist.github.com/lpinca/389b2fb022eee147d11a, still using a single client:
```
big buffer (ws): 1.05s 99.77 MB/s
big buffer (faye): 1.12s 93.96 MB/s
big buffer (lws): 3.29s 31.91 MB/s
big buffer (lws + bufferSize): 0.86s 122.21 MB/s
small buffers (ws): 1.25s 3.99 MB/s
small buffers (faye): 0.95s 5.25 MB/s
small buffers (lws): 0.66s 7.54 MB/s
small buffers (lws + bufferSize): 0.61s 8.09 MB/s
big buffer permessage-deflate (ws): 11.43s 9.18 MB/s
big buffer permessage-deflate (faye): 5.91s 17.73 MB/s
small buffers permessage-deflate (ws): 5.04s 988.11 kB/s
small buffers permessage-deflate (faye): 5.23s 951.09 kB/s
small buffers permessage-deflate (lws): 3.17s 1.57 MB/s
small buffers permessage-deflate (lws + bufferSize): 3.05s 1.63 MB/s
```

**Comment by alexhultman** [comment]
It's fine, I do spam myself and I like hearing benchmark results. I ran the (small) echo test with WebSocket++ and that server is *extremely* fast for small buffers! 160 echoes/ms. The larger buffer was faster in node-lws still :)
