### ISSUE TITLE
µWebSockets

### ISSUE THREAD

**Issue by alexhultman** [alexhultman/node-lws#47]
I'm working on a separate project to get some reference of what the expected top performance of a WebSocket server can be. In my testing I have found WebSocket++ quite extreme in its performance of echoing small messages (much faster than libwebsockets) so I wanted to see how much faster it could be done.

Currently I have an echo server that can echo small messages in ~310 echoes/ms, where WebSocket++ does ~300. µWebSockets is however consuming 6% the memory per connection.

I'm thinking, if anyone wants bloat-free (no WSS, no permessage deflate, no extensions, only version 13, etc) WebSockets I could maybe work on integrating this separate project as an alternative backend in node-lws. It would take some time to finish this project but it seems pretty simple actually.

**Comment by alexhultman** [comment]
Like, seriously? I can get 1 million connections like this:

Connection performance: 75.358 connections/ms
Memory performance: 3289.3 connections/mb

The process consumes 250 mb...

**Comment by alexhultman** [comment]
If anyone is interested in this (minimal) project: https://github.com/alexhultman/uWebSockets

**Comment by alexhultman** [comment]
Yes this is a good idea. You will be able to specify a server option 'uWebSockets' boolean to swap the underlying lws server for a uWS server. Then you get no SSL support, no permessage deflate but you get industry leading perf and memory usage.

When you need the other things you swap back to lws.

**Comment by LordMajestros** [comment]
I was going to ask if you would add this to lws. I really like this.

**Comment by alexhultman** [comment]
Yep it should actually be pretty simple. Just replace the pointer to a lws::Server with a pointer to a uWS::Server because they share a common interface. And since you can swap whenever you like, it doesn't matter that the micro thingy is lacking features.

**Comment by alexhultman** [comment]
I've come pretty far into this project. Far enough to run all benchmarks:

311 echoes/ms (ws: 26 echoes/ms)
>1.2 GB/sec throughput for 100 mb message echo (ws: 330MB/sec)
>3200 connections/mb ram (ws: 51 connections/mb)

**Comment by alexhultman** [comment]
Maybe it is best to separate the two projects after all. They are different and will diverge in functionality. I could do more with µWS than what I could with node-lws since I cannot mess around all I want in libwebsockets. It should be possible to integrate µWS more closely with Node.js if I wanted. I could in theory make use of the tls.TLSSocket to properly hand-off SSL from Node.js. Also, I should probably not bloat this project with other stuff.
