### ISSUE TITLE
maxMessageSize defaults to 0, should be about 16MB

### ISSUE THREAD

**Issue by mkozjak** [alexhultman/node-lws#49]
messages larger than 4096 bytes that are received on the server side using lws appear as an empty buffer ('message' event), as shown in the example:
```js
server.on('message', function (socket, message, binary)  {
    console.log('[Message: ' + message + ']');           // this is empty
});
```

are there any plans to support this?

edit: here's the mentioned limit, obviously: https://github.com/alexhultman/node-lws/blob/793a59cb338c6b1ed5487bcd342ee9526febca67/src/lws.cpp#L301

**Comment by alexhultman** [comment]
What version are you on?

**Comment by mkozjak** [comment]
0.7.0

Node 5.8 and 5.9.

**Comment by alexhultman** [comment]
Okay so I'm pretty sure I have received a 100 mb message. What size is the message you send? And what is the length of the message you get? Is it a specific length that doesn't work?

**Comment by mkozjak** [comment]
Anything that exceeds 4096 characters will fail. In example, my message is 11744 characters.
Packet size according to tcpdump is 11819 bytes (masked data).

I am not doing any kind of processing on the receiver while I'm reporting this.
If you do a console.log of 'message', you get '<Buffer >'.

For a valid message and 'console.log(message, message.length)', you'd get '<Buffer 75 69 64 5f 30> 5'.
Any messages above 4096 characters end up with '<Buffer > 0'.

I have also tried removing setUserData for a socket, but that didn't make any differences.

This happens on both OS X 10.11 and Ubuntu 15.10. Different ulimit values are set on those systems.

**Comment by alexhultman** [comment]
I just tested sending a 100 mb message and it was received as one buffer with length 104857600.

**Comment by alexhultman** [comment]
Are you sending messages in fragments? Or is it one large FIN:ed message?

**Comment by LordMajestros** [comment]
What size do you use for `bufferSize` and `maxMessageSize` when creating the server?

**Comment by mkozjak** [comment]
@alexhultman: As you can see from the dump (nok.cap), there is a packet numbered '9' which is of length 4161 byte and is FIN:ed. So no, I'm not sending any fragmented messages and yes, it's one large FIN:ed message.

@LordMajestros: Default. So that's probably a problem. :) :) :)

@alexhultman: There should probably be another argument for the ```message``` event for such cases. Or are we safe assuming the message is too large if 0 size appeared?

Thanks for helping!

**Comment by alexhultman** [comment]
What happens if you use the fragment event instead of the message event? Then you should probably get one fragment of length 4kb and one with length 1? Default maxMessageSize is 16MB so it shouldn't matter since you are just sending 4kb + 1byte

**Comment by mkozjak** [comment]
I used maxMessageSize and it helped (for the ```message``` event).

Yes, it works if I listen on ```fragment```, too!

**Comment by alexhultman** [comment]
That's strange because it should be 16MB by default. You are not talking about the bufferSize?

**Comment by mkozjak** [comment]
Haven't touched ```bufferSize```. Changing ```maxMessageSize``` helped in correctly receiving a message larger than 4096 through a ```message``` event.

**Comment by alexhultman** [comment]
Ah, okay I understand. I have a flaw in the default. I actually set the default maxMessageSize to 0. So you need to set it. I will fix this up for next version then.

**Comment by ronkorving** [comment]
Should it really be an arbitrary number like 16 MB? Infinity would be a nice default imho, though arguably unsafe by default. Clear documentation could mitigate that though.

**Comment by alexhultman** [comment]
The options needs documenting yes. I don't know I just don't want it to accept too much and die.

**Comment by LordMajestros** [comment]
I think 16mb is ok. It is a default after all and can be set by the programmer. It just needs to be documented. The current default of 0 throws unexpected surprises and should definitely be increased.
