### ISSUE TITLE
Identify a client connected and broadcast a message!

### ISSUE THREAD

**Issue by renesamaral** [alexhultman/node-lws#5]
Hi! How can i identify a user connected to send a message to a specific user? And how can i broadcast a message to all users connected?

**Comment by alexhultman** [comment]
I don't follow? A connection is represented by a socket which is passed as argument to the event handlers. If you want to "broadcast" you have to loop over the sockets and send. I can take a look at improving broadcast but under the surface it is pretty much just a loop anyways.

You can set custom data to a socket in the C++ wrapper but not yet in the Node.js wrapper.

**Comment by alexhultman** [comment]
I added an issue regarding broadcast #6

**Comment by alexhultman** [comment]
Are you talking about getting the IP of a client? This can be added.

**Comment by renesamaral** [comment]
Hi alex, ty for the fast answer and sorry for my low answer and for my english, its not so good! About the broadcast, its nice your idea about making the broadcast with some some extra optimizations to memory management! About identify the client, i intend to use json webtokens to auth the socket connections and some times send a message to a specified user! If i understand, i need to identify a socket connections when the event of 'connection' is emitted and store the connections in a array of connections and when i need to send a message to a specified user, i make a search in my array and send a message to the socket connection?

**Comment by alexhultman** [comment]
Yes when you get a connection you perform whatever authorization you need. You will probably need to set some custom data to the socket, which is not yet implemented (in the Node.js wrapper).

server.setUserData(socket, <some kind of value>) will be implemented (and getUserData). That way you can mark a socket as "unauthorized" until you have received enough messages to verify it.

**Comment by renesamaral** [comment]
Nice! I intend to use you node.js' wrapper instead of ws websocket implementation of einarious! i saw the 600k post and your parameters of memory and cpu consume are very nice! If you have a time and could implement this functionally in node.js wrapper too, It will be very valuable! Ty :)

**Comment by alexhultman** [comment]
Well, ws is pure crap so you are making a wise decision.

**Comment by renesamaral** [comment]
hahaha! Of course! But it was the fastest node websock implementation until you dev this wrapper for node!

**Comment by alexhultman** [comment]
setUserData / getUserData is now wrapped. It takes a string currently. Will be published as 0.0.11.
