### ISSUE TITLE
Maintainers / owners wanted

### ISSUE THREAD

**Issue by alexhultman** [alexhultman/node-lws#51]
I must say I have kind of lost interest in this project since µWebSockets. I cannot keep focus on two separate projects doing the same thing, where one is massively outperforming the other in all regards. If anyone want to maintain this (node-lws) project or even keep on developing new features that would be nice. Otherwise I wouldn't be surprised if this project gets overrun by my other project. My point is, in a not too far future µWebSockets will have basically the same feature set as node-lws.

**Comment by lpinca** [comment]
We added it in Primus exactly 1 month ago :smile:.
I wonder if the `lws` transformer fate is to be deprecated in favor of a `µws` transformer.

**Comment by alexhultman** [comment]
It would make a lot more sense to replace lws with µws in Primus. None of the two projects support SSL transfer and µws does (will) support Windows and have graceful shutdown and pass all Autobahn tests. SSL transfer is something I would like to try in µws first of all. µws is kind of node-lws v2.
