### ISSUE TITLE
Implement zero-copy sending

### ISSUE THREAD

**Issue by alexhultman** [alexhultman/node-lws#8]
The wrapper already has a pretty optimized sending function, but there is a possibility of sending with zero-copy. This requires the user to manage post and pre-padding of the Buffers sent.

**Comment by Rush** [comment]
How would that pre-padding work? How I usually send my messages is I do `JSON.stringify(object)`. I guess that zero-copy would be a good use case if somebody had those responses cached.

Maybe a utility like `lws.prepareBufferForSending` would suffice?

**Comment by alexhultman** [comment]
The idea is that you allocate a buffer that has a margin pre and post of your message. Then you pass this padded buffer to libwebsockets which will then fill in headers and footers without copying the message.

I will add some kind of helper function(s) for this but that is low priority since it already outperforms ws a lot.

**Comment by alexhultman** [comment]
For broadcasting, two simple functions like prepareBuffer and sendPrepared would be very efficient, yes:

var preparedBuffer = server.prepareBuffer(some Node.js buffer);
for all your sockets:
	server.sendPrepared(socket, preparedBuffer, false);
