### ISSUE TITLE
Future of node-lws

### ISSUE THREAD

**Issue by herkyl** [alexhultman/node-lws#9]
First of all great work so far! I'm very exited about a library more memory effective than ws.

Some questions about the future:
* Will it support the latest stable node.js versions (5.6.0 atm)
* Will it be tested against the Autobahn test suite?

**Comment by alexhultman** [comment]
Autobahn testing is not part of the wrapper. This happens in libwebsockets itself (already passed).

Node.js version support will depend on demand - I thought users were on 4.x now but if 5.x is already being used I will have to support both.

**Comment by herkyl** [comment]
I think most use the latest stable. Looking forward to testing this in production

**Comment by alexhultman** [comment]
I will supply pre-compiled binaries for 4.x & 5.x then.

**Comment by alexhultman** [comment]
There is now support for Node 4.x and 5.x

**Comment by herkyl** [comment]
@alexhultman you are looking for someone who can provide OSX builds. What is needed for this?

**Comment by alexhultman** [comment]
I wrote some instructions in the issue

måndag 15 februari 2016 skrev Serge <notifications@github.com>:
